### PR TITLE
Always run the test_end_expr, even if the test throws an exception.

### PR DESCRIPTION
**Pull request by NHDaly**
Put the test_end_expr running in a try/finally.

Also adds a debugv log for running the test_end_expr.
Adds tests.

--------

I made the following design decision:
- We run the test_end_expr iff we run the testitem.
    - i.e. If the testsetup fails or does not exist, we do not start the testitem and therefore do not run the test_end_expr.

Let me know if that doesn't sound right to you.

### CODE REVIEW

**Review by Drvi — APPROVED** [review]
LGTM, thanks!

**Review by nickrobinson251 — APPROVED** [review]
Thanks! LGTM

> We run the test_end_expr iff we run the testitem.
>  i.e. If the testsetup fails or does not exist, we do not start the testitem and therefore do not run the test_end_expr.

I think that's a good call! Is it worth adding a test for the case where we didn't get as far as running the test-item?

**Comment by NHDaly** [comment]
That's covered in the DontPass.jl tests already 👍 I was going to add a test for it, but there's already one there. Should I call that out explicitly?
```
        # This is the total number of testitems in DontPass.jl, minus those with
        # nonexistent testsetups, or errors in the testsetup.
        @test @atomic(end_expr_count.x) == 7
```

**Comment by nickrobinson251** [comment]
ah great, thanks! no, that's good as is -- i just didn't read the test carefully enough 😊 

looks like some CI jobs need to be retried, so i'll do that. unfortunately our tests are a little flaky 😭 😭

**Pull request merged**
